src/main/java/pe/edu/cibertec/virtualexam/model/Exam.java
package pe.edu.cibertec.virtualexam.model;

import javax.persistence.*;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.SystemException;
import java.util.List;
import java.util.Set;

@Entity
public class Exam {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    private String name;

    // TODO check: maybe it is unnecessary usage ofjavax.persistence.FetchType.EAGER.
    // TODO research on javax.persistence.CascadeType.PERSIST and check if if it is the recommended way to save entire hierarchies.
    @OneToMany(cascade = CascadeType.PERSIST, mappedBy = "exam", fetch = FetchType.EAGER)
    private Set<Question> questions;

    public static Exam getExam(Integer id) {
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        Query query = em.createQuery("select e from Exam e where e.id = ?1");
        query.setParameter(1, id);
        Exam singleResult = (Exam) query
                .getSingleResult();
        // TODO check maybe javax.persistence.EntityManager.close should always be called in a finally block?.
        em.close();
        return singleResult;
    }

    public static List<Exam> getAllExams() {
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        Query query = em.createQuery("select e from Exam e");
        List resultList = query
                .getResultList();
        em.close();
        return resultList;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Set<Question> getQuestions() {
        return questions;
    }

    public void setQuestions(Set<Question> questions) {
        this.questions = questions;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void save() throws HeuristicRollbackException, javax.transaction.RollbackException, HeuristicMixedException, SystemException {
        // TODO check: too much boilerplate code, try to simplify delegating tx management to framework/container.
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        em.getTransaction().begin();
        em.persist(this);
        em.getTransaction().commit();
        em.close();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Exam exam = (Exam) o;

        return id != null ? id.equals(exam.id) : exam.id == null;

    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}

src/main/java/pe/edu/cibertec/virtualexam/model/Student.java
package pe.edu.cibertec.virtualexam.model;

import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.Id;
import javax.persistence.Query;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

@Entity
public class Student {

    @Id
    private String username;
    private String password;
    private String fullName;

    public static Student findByUsernameAndPassword(String username, String password) {
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        // FIXME do not store the plain text password in the DB.
        Query query = em.createQuery("select e from Student e where e.username = ?1 and e.password = ?2");
        query.setParameter(1, username);
        query.setParameter(2, password);
        List list = query
                .getResultList();
        em.close();
        if (list.size() > 0) {
            return (Student) list.get(0);
        } else {
            return null;
        }
    }

    static List<Student> getAll() {
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        Query query = em.createQuery("select e from Student e");
        List resultList = query
                .getResultList();
        em.close();
        return resultList;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Set<ResolvedExam> getResolvedExams() {
        EntityManager em = EMFSingletonFactory.getEMF().createEntityManager();
        Query query = em.createQuery("select e from ResolvedExam e where e.student = ?1");
        query.setParameter(1, this);
        List<ResolvedExam> resolvedExamList = query
                .getResultList();
        for (ResolvedExam resolvedExam : resolvedExamList) {
            Set<Question> allExamQuestions = resolvedExam.getExam().getQuestions();
            double questionValue = 20.0 / allExamQuestions.size();
            double total = 0;
            for (Question currentQuestion : allExamQuestions) {
                List<Alternative> currentQuestionAlternatives = currentQuestion.getAlternatives();
                Set<Alternative> correctAlternativesForThisQuestion = new LinkedHashSet<>();
                for (Alternative alternative : currentQuestionAlternatives) {
                    if (alternative.isCorrect()){
                        correctAlternativesForThisQuestion.add(alternative);
                    }
                }
                Set<Alternative> chosenAlternativesForThisQuestion = new LinkedHashSet<>();
                for (SelectedAlternative selectedAlternative : resolvedExam.getSelectedAlternatives()) {
                    if (selectedAlternative.getAlternative().getQuestion().equals(currentQuestion)){ // Filtering the selected alternatives for this question only.
                        chosenAlternativesForThisQuestion.add(selectedAlternative.getAlternative());
                    }
                }
                if (chosenAlternativesForThisQuestion.equals(correctAlternativesForThisQuestion)){ // Sets with same size and items.
                    total += questionValue;
                }
            }
            // TODO evaluate to persist the rounded value instead of calculating it, so it could be simply queried later.
            total = Math.round(total);
            resolvedExam.setGrade(total);
        }
        // TODO check maybe javax.persistence.EntityManager.close should always be called in a finally block?.
        em.close();
        return new LinkedHashSet<>(resolvedExamList);
    }
}

src/main/java/pe/edu/cibertec/virtualexam/ExamDetailJSFBean.java
package pe.edu.cibertec.virtualexam;

import pe.edu.cibertec.virtualexam.model.Exam;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;

@ManagedBean
public class ExamDetailJSFBean {

    @ManagedProperty(value = "#{param.id}")
    private Integer examId;

    private Exam exam;

    public void setExamId(Integer examId) {
        this.examId = examId;
    }

    @PostConstruct
    public void init() {
        if (examId != null) {
            exam = Exam.getExam(this.examId);
        }
    }

    public Exam getExam() {
        return exam;
    }

}

src/main/java/pe/edu/cibertec/virtualexam/ExamJSFBean.java
package pe.edu.cibertec.virtualexam;

import org.apache.commons.lang.StringUtils;
import org.primefaces.component.commandbutton.CommandButton;
import org.primefaces.component.inputtext.InputText;
import org.primefaces.component.outputlabel.OutputLabel;
import org.primefaces.component.panel.Panel;
import org.primefaces.component.panelgrid.PanelGrid;
import pe.edu.cibertec.virtualexam.model.Alternative;
import pe.edu.cibertec.virtualexam.model.Exam;
import pe.edu.cibertec.virtualexam.model.Question;
import pe.edu.cibertec.virtualexam.util.Utils;

import javax.faces.application.Application;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.component.UIComponent;
import javax.faces.component.html.HtmlInputHidden;
import javax.faces.component.html.HtmlSelectBooleanCheckbox;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.servlet.http.HttpServletRequest;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

@ManagedBean
// TODO research on '@ViewScoped' and how does it maintain a Java object alive across requests.
@ViewScoped
// TODO determine what is the recommended naming style for a @ManagedBean class.
public class ExamJSFBean {

    private Exam exam;

    // NOTE that this variable state (actually its enclosing object itself) is being preserved between requests :).
    private int questionsCount;

    public ExamJSFBean() {
        // TODO check if it is possible that it gets created automatically.
        exam = new Exam();
    }

    public void addQuestion(ActionEvent event) {
        UIComponent questionsPanel = Utils.findComponent("questionsPanel");
        if (questionsPanel != null) {
            Panel questionPanel = new Panel();
            List<UIComponent> questionPanelChildren = questionPanel.getChildren();
            PanelGrid panelGrid = new PanelGrid();
            List<UIComponent> panelGridChildren = panelGrid.getChildren();
            panelGrid.setColumns(2);
            OutputLabel outputLabel = new OutputLabel();
            outputLabel.setValue("Pregunta");
            panelGridChildren.add(outputLabel);
            InputText questionInputText = new InputText();
            String questionId = "question_" + ++questionsCount;
            questionInputText.setId(questionId);
            panelGridChildren.add(questionInputText);
            questionPanelChildren.add(panelGrid);
            // TODO try avoid HTML line breaks everywhere.
            questionPanelChildren.add(Utils.createHtmlComponent("<br/>"));
            CommandButton addAlternativeCommandButton = new CommandButton();
            // TODO research on org.primefaces.component.commandbutton.CommandButton.setUpdate().
            addAlternativeCommandButton.setUpdate("questionsPanel");
            addAlternativeCommandButton.setValue("Añadir alternativa");
            addAlternativeCommandButton.addActionListener(new AddAlternativeActionListener());
            questionPanelChildren.add(addAlternativeCommandButton);
            questionPanelChildren.add(Utils.createHtmlComponent("<br/>"));
            questionPanelChildren.add(Utils.createHtmlComponent("<br/>"));
            HtmlInputHidden questionIdHiddenInput = new HtmlInputHidden();
            questionIdHiddenInput.setValue(questionId);
            questionPanelChildren.add(questionIdHiddenInput);
            PanelGrid multipleSelectionPanel = new PanelGrid();
            List<UIComponent> multipleSelectionPanelChildren = multipleSelectionPanel.getChildren();
            OutputLabel multipleSelectionLabel = new OutputLabel();
            multipleSelectionLabel.setValue("Selección múltiple");
            multipleSelectionPanelChildren.add(multipleSelectionLabel);
            Application application = FacesContext.getCurrentInstance().getApplication();
            HtmlSelectBooleanCheckbox multipleSelectionCheckbox = (HtmlSelectBooleanCheckbox)application.createComponent(HtmlSelectBooleanCheckbox.COMPONENT_TYPE);
            multipleSelectionCheckbox.setId(Utils.constructMultipleSelectionId(questionId));
            multipleSelectionPanelChildren.add(multipleSelectionCheckbox);
            questionPanelChildren.add(multipleSelectionPanel);
            questionPanelChildren.add(Utils.createHtmlComponent("<br/>"));
            questionsPanel.getChildren().add(questionPanel);
        }
    }

    public void save(ActionEvent event) throws IOException, HeuristicRollbackException, RollbackException, HeuristicMixedException, SystemException {

        //region Binding questions and alternatives manually.
        // TODO try to bind questions and alternatives automatically to JSF components, see pe.edu.cibertec.virtualexam.ExamJSFBean#exam for the candidate parent object.
        Set<Question> questions = new LinkedHashSet<>();
        for (int i = 1; i <= questionsCount; i++) {
            String questionId = "question_" + i;
            InputText questionInputText = (InputText) Utils.findComponent(questionId);
            Question question = new Question();
            question.setExam(exam);
            question.setText((String) questionInputText.getValue());
            List<Alternative> alternatives = new ArrayList<Alternative>();
            question.setMultipleSelection(((HtmlSelectBooleanCheckbox) Utils.findComponent(Utils.constructMultipleSelectionId(questionId))).isSelected());
            int idx = 0;
            boolean atLeastOneCorrectAlternativeAlreadySelected = false;
            while (true) {
                // TODO try to reuse this block, see pe.edu.cibertec.virtualexam.AddAlternativeActionListener.processAction().
                String alternativeId = Utils.constructAlternativeId(questionId, ++idx);
                InputText alternativeInputText = (InputText) Utils.findComponent(alternativeId);
                if (alternativeInputText == null) {
                    break;
                }
                String alternativeText = (String) alternativeInputText.getValue();
                Alternative alternative = new Alternative();
                alternative.setQuestion(question);
                alternative.setText(alternativeText);
                HtmlSelectBooleanCheckbox alternativeCheckbox = (HtmlSelectBooleanCheckbox) Utils.findComponent(Utils.constructCorrectAlternativeCheckboxName(alternativeId));
                boolean alternativeSelected = alternativeCheckbox.isSelected();
                if (!question.isMultipleSelection() && atLeastOneCorrectAlternativeAlreadySelected && alternativeSelected){
                    addValidationError("Para las preguntas de selección simple se debe marcar una sola alternativa.");
                    return;
                }
                alternative.setCorrect(alternativeSelected);
                atLeastOneCorrectAlternativeAlreadySelected |= alternativeSelected;
                alternatives.add(alternative);
            }
            if (!atLeastOneCorrectAlternativeAlreadySelected){
                addValidationError("Se debe seleccionar al menos una alternativa correcta para cada pregunta.");
                return;
            }
            question.setAlternatives(alternatives);
            questions.add(question);
        }

        exam.setQuestions(questions);
        //endregion

        //region Validation.
        // TODO research on JSF recommended validation facilities.
        // TODO check the validation mechanism so several validation problems could be reported to the user instead of only the first problem found with an immediate return.
        if (StringUtils.isBlank(exam.getName())) {
            addValidationError("El nombre del examen es requerido.");
            return;
        }

        if (exam.getQuestions().size() == 0) {
            addValidationError("Se requiere registrar al menos una pregunta.");
            return;
        }
        for (Question question : questions) {
            if (StringUtils.isBlank(question.getText())) {
                addValidationError("El texto para cada pregunta es requerido.");
                return;
            }
            if (!(question.getAlternatives().size() > 1)) {
                addValidationError("Se requiere que todas las preguntas tengan más de una alternativa.");
                return;
            }
            for (Alternative alternative : question.getAlternatives()) {
                if (StringUtils.isBlank(alternative.getText())) {
                    addValidationError("El texto para cada alternativa es requerido.");
                    return;
                }
            }
        }
        //endregion

        exam.save();
        triggerPageReload();
    }


    private void addValidationError(String summary) {
        FacesContext.getCurrentInstance().addMessage(null,
                new FacesMessage(FacesMessage.SEVERITY_WARN, summary, null));
    }

    // TODO check if this is the recommended JSF way to clean up all the view state.
    private void triggerPageReload() throws IOException {
        ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
        ec.redirect(((HttpServletRequest) ec.getRequest()).getRequestURI());
    }

    // TODO check if it would be OK (and possible) in design terms to call pe.edu.cibertec.virtualexam.model.Exam.getAllExams straight from the JSF view.
    public List<Exam> getAllExams() {
        return Exam.getAllExams();
    }

    public Exam getExam() {
        return exam;
    }

    public void setExam(Exam exam) {
        this.exam = exam;
    }
}

src/main/webapp/examDetails.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>#{examDetailJSFBean.exam.name}</h1>
            <p:dataList value="#{examDetailJSFBean.exam.questions}" var="question">
                <h:outputText value="#{question.text}"/>
                <br/>
                <br/>
                <p:dataList value="#{question.alternatives}" var="alternative" style="margin-top: 10px;">
                    #{alternative.text} <h:outputText value="(Correcta)" rendered="#{alternative.correct}"/>
                </p:dataList>
                <br/>
            </p:dataList>
            <br/>
            <p:link value="Regresar" outcome="exams.xhtml"/>
        </ui:define>
    </ui:composition>
</h:body>

</html>

src/main/webapp/exams.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">

            <!-- TODO research on this component and its attributes. -->
            <p:messages id="messages" autoUpdate="true" closable="true"/>

            <h1>Exámenes</h1>

            <p:dataList value="#{examJSFBean.allExams}" var="exam">
                <p:link value="#{exam.name}" outcome="examDetails.xhtml">
                    <f:param value="#{exam.id}" name="id"/>
                </p:link>
            </p:dataList>

            <!-- TODO look for the right way to create vertical space in JSF/PrimeFaces instead of using html line breaks and CSS margin styles. -->
            <br/>

            <p:commandButton value="Nuevo" onclick="PF('newExamPanel').show()"/>

            <br/>
            <br/>

            <p:panel visible="false" closable="true" toggleable="true" widgetVar="newExamPanel">
                <h:form>
                    <p:panelGrid columns="2">
                        <h:outputLabel value="Nombre de examen"/>
                        <h:inputText value="#{examJSFBean.exam.name}"/>
                    </p:panelGrid>
                    <br/>
                    <p:commandButton value="Añadir pregunta" actionListener="#{examJSFBean.addQuestion}"
                                     update="questionsPanel"/>
                    <br/>
                    <p:panelGrid id="questionsPanel" columns="1" style="margin-bottom: 10px;margin-top: 10px;">
                    </p:panelGrid>
                    <p:commandButton value="Registrar examen" actionListener="#{examJSFBean.save}"/>
                </h:form>
            </p:panel>

            <br/>

            <p:link value="Regresar" outcome="index.xhtml"/>

        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>Exámenes virtuales</h1>
            <p>Bienvenido administrador <strong>${username}</strong>.</p>
            <p:link value="Exámenes" outcome="exams.html"/>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>Inicio de sesión</h1>
            <h:form>
                <p:growl id="growl"/>
                <p:panelGrid>
                    <p:row>
                        <p:column>
                            <p:outputLabel value="Usuario"/>
                        </p:column>
                        <p:column>
                            <p:inputText value="#{loginJSFBean.username}"/>
                        </p:column>
                    </p:row>

                    <p:row>
                        <p:column>
                            <p:outputLabel value="Contraseña"/>
                        </p:column>
                        <p:column>
                            <p:password value="#{loginJSFBean.password}"/>
                        </p:column>
                    </p:row>

                    <p:row>
                        <p:column colspan="2">
                            <!-- TODO manage usability considerations after pressing this button and receiving a failure, e.g. focus on username/password field. -->
                            <p:commandButton value="Ingresar" action="#{loginJSFBean.doLogin}" update="growl"/>
                        </p:column>
                    </p:row>
                </p:panelGrid>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/studentHome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:ui="http://java.sun.com/jsf/facelets"
>
<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <h1>Exámenes virtuales</h1>
            <p>Bienvenido ${sessionScope.student.fullName} (código: ${sessionScope.username}).</p>
            <h2>Rendir examen</h2>
            <p:dataList value="#{studentHomeJSFBean.pendingExams}" var="exam">
                <p:link value="#{exam.name}" outcome="takeExam.xhtml">
                    <f:param value="#{exam.id}" name="id"/>
                </p:link>
            </p:dataList>
            <h2>Exámenes resueltos</h2>
            <p:dataList value="#{studentHomeJSFBean.resolvedExams}" var="resolvedExam">
                <strong><h:outputText value="#{resolvedExam.exam.name}"/></strong>, <h:outputText
                    value="nota obtenida: #{resolvedExam.grade}"/>
            </p:dataList>

            <br/>
        </ui:define>
    </ui:composition>
</h:body>
</html>

src/main/webapp/takeExam.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core">

<h:body>
    <ui:composition template="WEB-INF/templates/template.xhtml">
        <ui:define name="content">
            <p:messages id="messages" autoUpdate="true" closable="true"/>
            <h1>#{takeExamJSFBean.exam.name}</h1>
            <h:form>
                <p:dataList value="#{takeExamJSFBean.questionsAndChoosenAlternativeId.entrySet()}" var="question">
                    <h:outputText value="#{question.key.text }"/>

                    <br/>

                    <p:selectOneRadio value="#{takeExamJSFBean.questionsAndChoosenAlternativeId[question.key]}" rendered="#{!question.key.multipleSelection}">
                        <f:selectItems value="#{question.key.alternatives}" var="q" itemLabel="#{q.text}"
                                       itemValue="#{q.id}"/>
                    </p:selectOneRadio>

                    <p:selectManyCheckbox value="#{takeExamJSFBean.questionsAndChoosenAlternativeId[question.key]}" rendered="#{question.key.multipleSelection}">
                        <f:selectItems value="#{question.key.alternatives}" var="q" itemLabel="#{q.text}"
                                       itemValue="#{q.id}"/>
                    </p:selectManyCheckbox>

                    <br/>
                </p:dataList>
                <br/>
                <p:commandButton value="Enviar" actionListener="#{takeExamJSFBean.submitAnswers}"/>
            </h:form>
            <br/>
            <p:link value="Regresar" outcome="studentHome.xhtml"/>
        </ui:define>
    </ui:composition>
</h:body>

</html>